# This is a basic workflow to help you get started with Actions

name: Check the source code

# Controls when the action will run.
on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Test
        run: npm run test
      - name: Prettier
        run: npm run prettier:format
      - name: Lint
        run: npm run lint:format
      - name: Pre Deploy
        run: npm run build
      - name: Deploy
        run: npm run deploy
